development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  #database: spreeBSC_v2-1-3dev
  database: spree_dynamic_upgrade
  pool: 5
  #username: postgres
  username: doug
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  
  database: spree_dynamic_test
  #database: spreeBSC_test
  
  pool: 5
  #username: postgres
  username: doug
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  
  database: spree_dynamic_production
  #database: spreeBSC_production
  
  pool: 5
  #username: postgres
  username: doug
  host: localhost
  